# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Paul Gambill
tagline:          'Product Manager and Entrepreneur'
description:      'Product Manager and Entrepreneur'
url:              https://paulgambill.com
baseurl:          /

author:
  name:           'Paul Gambill'
  url:            https://twitter.com/paulgambill
