# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Paul Gambill
tagline:          'Entrepreneur and Systems Thinker'
description:      'Entrepreneur and Systems Thinker'
url:              https://paulgambill.com
baseurl:          /

author:
  name:           'Paul Gambill'
  url:            https://twitter.com/paulgambill
