# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Paul Gambill
tagline:          'Product Manager and Entrepreneur'
description:      ''
url:              https://paulgambill.com
baseurl:          /

author:
  name:           'Paul Gambill'
  url:            https://twitter.com/paulgambill

#paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
